# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FHu-Oyy6lCW3YK18onWqg7uvKnK5-CxL
"""

import numpy as np
import random
from timeit import timeit

# Define addition functions
def add_python(Z1, Z2):
    return [z1 + z2 for z1, z2 in zip(Z1, Z2)]

def add_numpy(Z1, Z2):
    return np.add(Z1, Z2)

# Generate random sample data
Z1 = random.sample(range(1000), 100)
Z2 = random.sample(range(1000), 100)

# Time the execution of each function
python_time = timeit("add_python(Z1, Z2)", globals=globals(), number=1000)
numpy_time  = timeit("add_numpy(Z1, Z2)", globals=globals(), number=10000)

# Print results
print(f"Pure Python addition: {python_time:.2f} s per loop")
print(f"NumPy addition: {numpy_time:.2f} s per loop")

import numpy as np

zeros_arr = np.zeros((2,3))
print(zeros_arr)

import numpy as np
array = np . array ([[1 , 2 , 3] , [4 , 5 , 6]]) # Shape (2 , 3)
reshaped_array = array . reshape (3 , 2) # Reshape to (3 ,2, keeping 6 elements
print (" Original Shape :", array . shape , "\ nReshaped Shape :", reshaped_array . shape )

import numpy as np
a = np . arange (1 , 10)
print ( a )
x = range (1 , 10)
print ( x ) # x is an iterator
print ( list ( x ) )
x = np . arange (10.4)
print ( x )
x = np . arange (0.5 , 10.4 , 0.8)
print ( x )

for i in range(1, 11):
    print(i)

print ( np . linspace (1 , 10 , 7) )
# excluding the endpoint :
print ( np . linspace (1 , 10 , 7 , endpoint = False ) )

import numpy as np
array_from_list = np . array ([1 , 2 , 3]) # [1 2 3]
array_from_tuple = np . array ((4 , 5 , 6) ) # [4 5 6]
array_from_nested_list = np . array ([[1 , 2 , 3] , [4 , 5 ,6]]) # [[1 2 3] [4 5 6]]
print ( array_from_list , array_from_tuple ,array_from_nested_list , sep ='\n')

import numpy as np
# Existing Array of Shape :(2 ,3)
arr = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
# Creating Array with Shape of existing array :
zeros , ones , empty = np . zeros ( arr . shape ) , np . ones (arr . shape ) , np . empty ( arr . shape ) # Shape : (2 ,3)
print ( arr , zeros , ones , empty , sep ='\n')

import numpy as np
array = np . array ([1 , 2 , 3])
# Multiplies each element by 2 , result : [2 , 4 , 6]
new_array = array * 2
# Creates a new array with the same elements
copied_array = np . copy ( array )
# Slices elements from index 1 to 3 , result :[2]
sliced_array = array [1:2]

import numpy as np
arr1 = np . array ([[1 , 2] , [3 , 4]]) # Shape : (2 , 2)
arr2 = np . array ([[5 , 6] , [7 , 8]]) # Shape : (2 , 2)
# Stacking examples
hstacked = np . hstack (( arr1 , arr2 ) )
# Output hstack : [[1 2 5 6] [3 4 7 8]]
vstacked = np . vstack (( arr1 , arr2 ) )
# Output vstack [[1 2] [3 4] [5 6] [7 8]]
colstacked = np . column_stack (( arr1 [0] , arr2 [0]) )
# Output column stack : [[1 5] [2 6]]
print ( hstacked , vstacked , colstacked , sep ='\n')

import numpy as np
arr1 = np . array ([[1 , 2] , [3 , 4]]) # Shape : (2 , 2)
arr2 = np . array ([[5 , 6] , [7 , 8]]) # Shape : (2 , 2)
concat_axis0 = np . concatenate (( arr1 , arr2 ) , axis =0)
# Concatenate along axis 0 ( vertical ) Shape : (4 , 2)
concat_axis1 = np . concatenate (( arr1 , arr2 ) , axis =1)
# Concatenate along axis 1 ( horizontal ) Shape : (2 , 4)
print ( concat_axis0 , concat_axis1 , sep ='\n')

import numpy as np
# Arrays
arr1d = np . array ([0 , 1 , 2 , 3 , 4 , 5])
arr2d = np . array ([[0 , 1 , 2] , [3 , 4 , 5] , [6 , 7 , 8]])
arr3d = np . array ([[[0 , 1] , [2 , 3]] , [[4 , 5] , [6 , 7]] , [[8 ,9] , [10 , 11]]])
# Slicing examples
print (" Basic :", arr1d [1:4] , arr2d [1:3 , 0:2] , arr3d [1:2 , 0:2 ,1:2])
# Output Basic : arr1d :[1 2 3] arr2d :[[3 4] [6 7]] arr3d:[[[5] [7]]]
print (" Step :", arr1d [1:5:2] , arr2d [::2 , 1::2] , arr3d [::2 ,::2 , 1::2])
# Output : Step : [1 3] [[1] [7]] [[[1] [9]]]

import numpy as np
arr1 = np . array ([1 , 2 , 3])
arr2 = np . array ([4 , 5 , 6])
print ("Add:", np . add ( arr1 , arr2 ) ) # Output Add: [5 7 9]
print (" Subtract :", np . subtract ( arr1 , arr2 ) )
# Output Subtract : [ -3 -3 -3]
print (" Divide :", np . divide ( arr1 , arr2 ) )
# Output Divide : [0.25 0.4 0.5 ]
print (" Multiply :", np . multiply ( arr1 , arr2 ) )
# Output Multiply : [ 4 10 18]
print (" Power :", np . power ( arr1 , arr2 ) )
# Output Power : [ 1 32 729]
print ("Exp:", np . exp ( arr1 ) )
# Output Exp: [ 2.71828183 7.3890561 20.08553692]