# -*- coding: utf-8 -*-
"""deepkalashrestha_worksheet1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxwf_HmsMrOEQpkSiSrhowwL-w0vpq4O
"""

4.1

import numpy as np
arr = np.empty((2,2))
print(arr)

arr = np.ones((4,2))
print(arr)

arr = np.full((4,2), 13)
print(arr)

arr = [[1,2], [3,4]]
arr2 = np.zeros_like(arr)
print(arr2)

arr = [[1,2], [3,4]]
arr2 = np.ones_like(arr)
print(arr2)

new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

"""4.1.1"""

arr = np.arange(10, 50)
print(arr)

arr=np.arange(0,9)
reshape_arr=arr.reshape(3,3)
print(reshape_arr)

arr= np.eye(3)
print(arr)

import random as random
arr = np.random.random(30)
print(arr)
mean= np.mean(arr)
print(f"mean is {mean}")

arr= np.random.random((10,10))
max= np.max(arr)
min=np.min(arr)
print(f"max is {max} and min is {min}")

arr=np.zeros(10)
print(arr)
arr[4]=1
print(arr)

arr=[1, 2, 0, 0, 4, 0]
reverse = np.flip(arr)
print(reverse)

n,m = 5, 5
arr = np.zeros((n,m))
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)

checkboard=np.ones((8,8))
checkboard[1::2, ::2]=0
checkboard[::2, 1::2]=0
print(checkboard)

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(np.add(x,y))
print(np.add(v,w))
print(np.subtract(x,y))
print(np.subtract(v,w))
print((x,y)*2)
print((v,w)*5)
print(np.square(x))
print(np.square(y))
print(np.square(v))
print(np.square(w))
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))
print(np.concatenate((x,y), axis=0))#row concatenation
#v anw w reshape
v=v.reshape(2,1)
w=w.reshape(2,1)
print(np.concatenate((v,w), axis=1))#column concatenation
print(np.concatenate((x,v), axis =1))
#print(np.concatenate((x,v), axis=0))# same as above diff dimension

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inverse=np.linalg.inv(A)
print(np.dot(A, A_inverse))
print(np.dot(A,B))
print(np.dot(B,A))
AB = np.dot(A,B)
at= np.transpose(A)
bt= np.transpose(B)
print(np.dot(at,bt))

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)
print(X)

import timeit
list1 = list(range(1000000))
list2 = list(range(1000000))

from timeit import timeit
def add_python(Z1, Z2):
  return [z1 + z2 for z1, z2 in zip(Z1, Z2)]
def add_numpy(Z1, Z2):
  return np.add(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("add_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python addition: {python_time:.2f} s per loop")
print(f"Numpy addition: {numpy_time:.2f} s per loop")

from timeit import timeit
def mul_python(Z1, Z2):
  return [z1 * z2 for z1, z2 in zip(Z1, Z2)]
def mul_numpy(Z1, Z2):
  return np.multiply(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("mul_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("mul_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python multiplication: {python_time:.2f} s per loop")
print(f"Numpy multiplication: {numpy_time:.2f} s per loop")

from timeit import timeit
def dot_python(Z1, Z2):
  return sum(z1 * z2 for z1, z2 in zip(Z1, Z2))
def dot_numpy(Z1, Z2):
  return np.dot(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("dot_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("dot_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python dot product: {python_time:.2f} s per loop")
print(f"Numpy dot product: {numpy_time:.2f} s per loop")

from timeit import timeit
matrix1 = np.random.random((1000, 1000))
matrix2 = np.random.random((1000, 1000))
list1 = matrix1.tolist()
list2 = matrix2.tolist()
def matrix_python(list1, list2):
  list2_T = list(zip(*list2))
  return [[sum(a*b for a,b in zip(list1_row,list2_col)) for list2_col in list2_T] for list1_row in list1]
def matrix_numpy(matrix1, matrix2):
  return np.matmul(matrix1, matrix2)
#Z1 = random.sample(range(1000000), 10000)
#Z2 = random.sample(range(1000000), 10000)
python_time = timeit("matrix_python(list1,list2)", globals=globals(), number=1)
numpy_time = timeit("matrix_numpy(matrix1,matrix2)", globals=globals(), number=1)
print(f"Pure Python matrix multiplication: {python_time:.2f} s per loop")
print(f"Numpy matrix multiplication: {numpy_time:.2f} s per loop")